query GeneOntology($ensemblId: String!) {
    target(ensemblId: $ensemblId) {
        id
        geneOntology {
            term {
                id
                label
                __typename
            }
            aspect
            evidence
            geneProduct
            source
            __typename
        }
        __typename
    }
}
