query GWASCredibleSetsQuery($studyId: String!, $size: Int!, $index: Int!) {
    study(studyId: $studyId) {
        id
        credibleSets(page: { size: $size, index: $index }) {
            count
            rows {
                studyLocusId
                variant {
                    id
                    chromosome
                    position
                    referenceAllele
                    alternateAllele
                    __typename
                }
                pValueMantissa
                pValueExponent
                beta
                locus {
                    count
                    __typename
                }
                finemappingMethod
                confidence
                l2GPredictions(page: { size: 1, index: 0 }) {
                    rows {
                        target {
                            id
                            approvedSymbol
                            __typename
                        }
                        score
                        __typename
                    }
                    __typename
                }
                __typename
            }
            __typename
        }
        __typename
    }
}
